Add c++ & python test case for resnet50 model
PaddlePaddle/continuous_integration pull request #5
Opened 2020-03-09 11:38 UTC by OliverLPH

Add c++ & python test case for resnet50 model

2020-03-09 11:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/continuous_integration?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/continuous_integration?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/continuous_integration?pullRequest=5) it.</sub>

2020-03-09 11:53 UTC, chalsliu requested changes
这里写不同的case吧，不然生成的xml会覆盖

2020-03-09 11:59 UTC, chalsliu commented on inference/inference_api_test/cpp_api_test/bin/resnet.sh
> +
这里写不同的case吧 通过参数指定 生成的xml会覆盖

2020-03-09 11:59 UTC, chalsliu commented on inference/inference_api_test/cpp_api_test/build.sh
> +export PATH=/opt/compiler/gcc-4.8.2/bin:$PATH
不要在这里指定编译器

2020-03-09 11:59 UTC, chalsliu commented on inference/inference_api_test/cpp_api_test/build.sh
> +exit 0
exit 0 可以去掉

2020-03-09 11:59 UTC, chalsliu commented on inference/inference_api_test/cpp_api_test/src/test_resnet50.cc
> +        //std::vector<PaddleTensor>{std::move(images), std::move(labels)});
这行注释去掉吧

2020-03-09 12:40 UTC, OliverLPH commented on inference/inference_api_test/cpp_api_test/src/test_resnet50.cc
> +        //std::vector<PaddleTensor>{std::move(images), std::move(labels)});
done

2020-03-09 12:40 UTC, OliverLPH commented on inference/inference_api_test/cpp_api_test/build.sh
> +exit 0
done

2020-03-09 12:41 UTC, OliverLPH commented on inference/inference_api_test/cpp_api_test/build.sh
> +export PATH=/opt/compiler/gcc-4.8.2/bin:$PATH
done

2020-03-09 12:41 UTC, OliverLPH commented on inference/inference_api_test/cpp_api_test/bin/resnet.sh
> +
done

2020-03-11 09:39 UTC, chalsliu approved these changes
LGTM

2020-03-11 09:55 UTC, merged